service: coupon-reminders

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: us-west-1
  stage: ${opt:stage, "dev"}
  lambdaHashingVersion: "20201221"

functions:
  app:
    package:
      include:
        - "coupon_reminders"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
        - ".pytest_cache"
        - "tests/**"
        - ".gitignore"
        - "poetry.lock"
        - "pyproject.toml"
        - "README.md"
        - "dist/**"
        - "tesseract/**"
    handler: coupon_reminders.main.handler
    timeout: 60
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: TesseractAl2LambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile

layers:
  tesseractAl2:
    path: ./tesseract
    compatibleRuntimes:
      - python3.8