service: coupon-reminders

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: us-west-1
  stage: ${opt:stage, "dev"}
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:
        - { "Fn::GetAtt": ["CouponsDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - { "Fn::GetAtt": ["CouponsS3Bucket", "Arn"] }
  environment:
    COUPONS_TABLE: ${self:custom.couponsTableName}
    COUPONS_BUCKET: ${self:custom.couponsBucketName}

functions:
  app:
    package:
      include:
        - "coupon_reminders"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
        - ".pytest_cache"
        - "tests/**"
        - ".gitignore"
        - "poetry.lock"
        - "pyproject.toml"
        - "README.md"
        - "dist/**"
        - "tesseract/**"
    handler: coupon_reminders.main.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /{proxy+}
          method: any
  coupon_processor:
    package:
      include:
        - "coupon_reminders"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
        - ".pytest_cache"
        - "tests/**"
        - ".gitignore"
        - "poetry.lock"
        - "pyproject.toml"
        - "README.md"
        - "dist/**"
        - "tesseract/**"
    handler: coupon_reminders.coupon_processor.handler
    timeout: 60
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: TesseractAl2LambdaLayer }
    events:
      - s3:
          bucket: ${self:custom.couponsBucketName}
          event: s3:ObjectCreated:*
          existing: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile
  couponsTableName: 'coupons-table-${self:provider.stage}'
  couponsBucketName: 'coupons-bucket-${self:provider.stage}'

resources:
  Resources:
    CouponsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.couponsTableName}
    CouponsS3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:custom.couponsBucketName}

layers:
  tesseractAl2:
    path: ./tesseract
    compatibleRuntimes:
      - python3.8